spring:
  application:
    name: telegram-gpt-chat-service
  config:
    import: "sm://"
  datasource:
    username: admin
    password: ${sm://postgres-db-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gcp:
      sql:
        database-name: ${sm://cloud-db-name}
        instance-connection-name: ${sm://cloud-db-instance-name}
  mvc:
    hiddenmethod:
      filter:
        enabled: true

app:
  mainAdmin:
    name: admin

telegram-bot-api:
  name: tg_gpt_chat_service_bot
  token: ${sm://telegram-bot-api-key}
  text:
    model: gpt-3.5-turbo
    temperature: 0.7
    max-tokens: 500
    top-p: 1
    frequency-penalty: 0
    presence-penalty: 0
chat-gpt-api:
  token: Bearer ${sm://chat-gpt-api-key}
  url:
    completions: https://api.openai.com/v1/chat/completions